In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('100_Unique_QA_Dataset.csv')
df.head()

,question,answer
0,What is the capital of France?,Paris
1,What is the capital of Germany?,Berlin
2,Who wrote 'To Kill a Mockingbird'?,Harper-Lee
3,What is the largest planet in our solar system?,Jupiter
4,What is the boiling point of water in Celsius?,100


tokenize

In [3]:
def tokenize(text):
    text=text.lower()
    text=text.replace('?','')
    text=text.replace("'","")
    text=text.replace('"','')
    return text.split()

In [4]:
tokenize('My na"m"e?')

['my', 'name']

vocab


In [5]:
vocab={'<UNK>':0}

In [6]:
def build_vocab(row):
    # print(row['question'],row['answer'])
    tokenized_question=tokenize(row['question'])
    tokenized_answer=tokenize(row['answer'])
    merged_tokens=tokenized_question+tokenized_answer
    print(merged_tokens)
    for token in merged_tokens:
        if token not in vocab:
            vocab[token]=len(vocab)

In [7]:
df.apply(build_vocab, axis=1)

['what', 'is', 'the', 'capital', 'of', 'france', 'paris']
['what', 'is', 'the', 'capital', 'of', 'germany', 'berlin']
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird', 'harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system', 'jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius', '100']
['who', 'painted', 'the', 'mona', 'lisa', 'leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64', '8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold', 'au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end', '1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world', 'nile']
['what', 'is', 'the', 'capital', 'of', 'japan', 'tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity', 'albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit', '32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet', 'mars']
['who', 'is', 'the', 'author', 'of', '19

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [8]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'unit

words to numerical indeces

In [9]:
def text_to_indices(text, vocab):
    indexed_text=[]
    for token in tokenize(text):
        if token in vocab:
            indexed_text.append(vocab[token])
        else:
            indexed_text.append(vocab['<UNK>'])
    return indexed_text


In [10]:
text_to_indices('What is nepal',vocab)

[1, 2, 0]

In [11]:
import torch
from torch.utils.data import DataLoader,Dataset

In [12]:
class QADataset(Dataset):
    def __init__(self,df, vocab):
        self.df=df
        self.vocab=vocab

    def __len__(self):
        return len(self.df)

    def __getitem__(self,index):
        numerical_question=text_to_indices(self.df.iloc[index]['question'],self.vocab)
        numerical_answer=text_to_indices(self.df.iloc[index]['answer'],self.vocab)
        return torch.tensor(numerical_question),torch.tensor(numerical_answer)


In [13]:
dataset=QADataset(df,vocab)

In [14]:
dataset[10]

(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [15]:
dataloader=DataLoader(dataset, batch_size=1, shuffle=True)

In [16]:
for question, answer in dataloader:
    print("Question:", question)
    print("Answer:", answer)


Question: tensor([[  1,   2,   3,  69,   5, 155]])
Answer: tensor([[156]])
Question: tensor([[ 10,  29, 130, 131]])
Answer: tensor([[132]])
Question: tensor([[ 10,  11, 189, 158, 190]])
Answer: tensor([[191]])
Question: tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]])
Answer: tensor([[268]])
Question: tensor([[  1,   2,   3, 122, 123,  19,   3,  45]])
Answer: tensor([[124]])
Question: tensor([[42, 18,  2, 62, 63,  3, 64, 18]])
Answer: tensor([[65]])
Question: tensor([[ 42, 107,   2, 108,  19, 109]])
Answer: tensor([[110]])
Question: tensor([[ 10,  75,   3, 296,  19, 297]])
Answer: tensor([[298]])
Question: tensor([[ 10,  11, 157, 158, 159]])
Answer: tensor([[160]])
Question: tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]])
Answer: tensor([[6]])
Question: tensor([[ 42, 167,   2,   3,  17, 168, 169]])
Answer: tensor([[170]])
Question: tensor([[ 1,  2,  3,  4,  5, 53]])
Answer: tensor([[54]])
Question: tensor([[  1,   2,   3, 146, 147,  19, 148]])
Answer: tensor([[149]])
Question: ten

rnn

In [17]:
import torch.nn as nn

In [42]:
 class SimpleRNN(nn.Module):
    def __init__(self,vocab_size):
        super().__init__()
        self.embedding=nn.Embedding(vocab_size,embedding_dim=50)
        self.rnn=nn.RNN(50,64,batch_first=True)
        self.fc=nn.Linear(64,vocab_size) 
    def forward(self, question):
        embedded_ques=self.embedding(question)
        hidden,final = self.rnn(embedded_ques)
        logits = self.fc(final).squeeze(0)
        return logits

In [43]:
lr=0.001
epochs=20

In [44]:
model=SimpleRNN(len(vocab))


In [45]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(), lr=lr)

In [56]:
for epoch in range(epochs):
    total_loss=0
    for question ,answer in dataloader:
     optimizer.zero_grad()

     #forward pass
     output=model(question)

     #loss
     loss=criterion(output,answer[0])

     #gradient
     loss.backward()

     #update
     optimizer.step()
     total_loss += loss.item()
    
    print(f"Epoch {epoch+1}, Loss: {total_loss:4f}")


Epoch 1, Loss: 0.536122
Epoch 2, Loss: 0.508909
Epoch 3, Loss: 0.482856
Epoch 4, Loss: 0.458955
Epoch 5, Loss: 0.436097
Epoch 6, Loss: 0.414797
Epoch 7, Loss: 0.394066
Epoch 8, Loss: 0.374913
Epoch 9, Loss: 0.356396
Epoch 10, Loss: 0.339240
Epoch 11, Loss: 0.322692
Epoch 12, Loss: 0.306937
Epoch 13, Loss: 0.292347
Epoch 14, Loss: 0.278146
Epoch 15, Loss: 0.264897
Epoch 16, Loss: 0.252574
Epoch 17, Loss: 0.240540
Epoch 18, Loss: 0.229281
Epoch 19, Loss: 0.218617
Epoch 20, Loss: 0.208357


In [58]:
def predict(model,question,threshold=0.5):
    numerical_ques=text_to_indices(question,vocab)

    ques_tensor=torch.tensor(numerical_ques).unsqueeze(0)

    output=model(ques_tensor)

    probs=torch.nn.functional.softmax(output,dim=1)

    value,index= torch.max(probs,dim=1)

    if value< threshold:
        print('I dont know')
    return list(vocab.keys())[index]

In [61]:
predict(model,'What is the capital of India')

'delhi'

In [ ]:
dataset[0][0]

tensor([1, 2, 3, 4, 5, 6])

In [23]:
x=nn.Embedding(324,50)

In [24]:
a=x(dataset[0][0])

In [25]:
x(dataset[0][0]).shape

torch.Size([6, 50])

In [26]:
y=nn.RNN(50,64)

In [27]:
y(a)[0].shape

torch.Size([6, 64])

In [28]:
y(a)[0]

tensor([[-0.0148,  0.5784, -0.4398, -0.6905,  0.4150, -0.5578, -0.1477,  0.4423,
          0.3055,  0.0565,  0.8318, -0.8152,  0.1209,  0.2325, -0.1624, -0.3882,
         -0.3464,  0.1648, -0.5787, -0.5280,  0.2937, -0.5023,  0.5690, -0.3189,
         -0.0995,  0.5178,  0.5912,  0.5131, -0.2561,  0.5574,  0.1085, -0.8539,
          0.0243, -0.2016, -0.7348, -0.7761, -0.4702, -0.5118, -0.2001,  0.5660,
         -0.3748,  0.6702,  0.7440,  0.8414, -0.3279,  0.2394, -0.0086,  0.3678,
          0.1639, -0.6088, -0.6930,  0.0047, -0.6545, -0.8163, -0.8158, -0.3229,
         -0.3568,  0.4244,  0.0394, -0.5312,  0.7101, -0.4142, -0.3486,  0.4219],
        [-0.2436,  0.2084,  0.8350, -0.3550,  0.7295,  0.7220, -0.3804, -0.8426,
          0.9200,  0.4902,  0.2506,  0.7723, -0.4959, -0.1161, -0.9837, -0.1677,
         -0.7734,  0.0904,  0.0021, -0.0143,  0.1785, -0.1964, -0.2263, -0.2647,
          0.1224,  0.1412, -0.7964, -0.8902,  0.1882,  0.5056, -0.0354,  0.0954,
          0.5192,  0.3477, 

In [29]:
b=y(a)[1]

In [30]:
y(a)[1].shape

torch.Size([1, 64])

In [31]:
z=nn.Linear(64, 324)

In [32]:
z(b).shape

torch.Size([1, 324])

In [33]:
a.shape

torch.Size([6, 50])

In [36]:
a=dataset[0][0].reshape(1,6)
a

tensor([[1, 2, 3, 4, 5, 6]])